language: java
services:
  - docker
before_install:
  - source <(curl -fsSL https://raw.github.com/daisy/maven-parents/travis/before_install)
script:
  - make docker &&
    make check-docker
after_success:
  - if [ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      mvn deploy:deploy;
    fi
before_cache:
  - source <(curl -fsSL https://raw.github.com/daisy/maven-parents/travis/before_cache)
cache:
  directories:
    - $HOME/.m2/cached-repository
    - src/main/docker
branches:
  except:
    - /^rd-/
